### ISSUE TITLE
StochasticGradientDescent fail tests

### ISSUE THREAD

**Issue by ReenExe** [gburtini/Learning-Library-for-PHP#6]
This class
https://github.com/gburtini/Learning-Library-for-PHP/blob/master/lib/parametric/regression/stochastic_gradient_descent.php

has tests:
https://github.com/gburtini/Learning-Library-for-PHP/blob/master/tests/stochastic_gradient_descent_test.php

and for continue move https://github.com/gburtini/Learning-Library-for-PHP/pull/5 - need fix it

**Comment by gburtini** [comment]
This should be fixed in 9e9116c4d8521477991a8e1883c2f30712a2b5cc -- I didn't dig deep in to why the learning rate was too large, but any learning rate of a reasonable size (0.02 is a pretty large learn for stochastic GD) seems to work. You can pull / merge this change in to the composer-ready branch or simply change the learning rate to 0.002 in the test.

Anything larger and it explodes to NaN. The learning rate stuff for SGD could benefit from some error checking/detection/warning, especially when the results start to move towards infinity.

**Comment by ReenExe** [comment]
Thank you, also corrected in the branch `PHPUnit`
